### PR TITLE
[SYCL] updates to oneapi compiler documentation

### PR DESCRIPTION
**Pull request by abagusetty**

### CODE REVIEW

**Comment by cjknight** [comment]
I think module loading and compilation example on this page should be updated, right?

 https://docs.alcf.anl.gov/polaris/compiling-and-linking/oneapi-compiler/

**Comment by abagusetty** [comment]
> 

Yes, the details were updated in this PR already. Since there is no versioning involved in the module naming. The module instructions & compilation command remains the same. Changes are mostly cosmetic. Still working on the PR, will convert it into a draft. It was just hosted as a PR to view the final markdown webpage.

**Comment by cjknight** [comment]
The oneapi-compiler page seems to tell users to load a special oneapi module path and then load the 'compiler' module. The sycl-polaris page instructs users to simply load the 'oneapi' module, which I believe is the one that you maintain.

**Comment by abagusetty** [comment]
> The oneapi-compiler page seems to tell users to load a special oneapi module path and then load the 'compiler' module. The sycl-polaris page instructs users to simply load the 'oneapi' module, which I believe is the one that you maintain.

Gotcha. I agree, it is just the result of bad naming conventions for the modules. The intent was to name `oneapi/release` for the release version (oneapi-compiler page) and the open-source (sycl-polaris page) version to be `oneapi/upstream`. And make `oneapi/release` as default. Please let me know if this clears the confusion or any other suggestion.

**Pull request merged**
