### PR TITLE
fix list formatting

### PR DESCRIPTION
**Pull request by cjknight**
@argonne-lcf/docs does this ping everyone?

### CODE REVIEW

**Review by ye-luo — APPROVED** [review]
Spot on

**Comment by weallcock** [comment]
I was going to review this, but it isn't clear what I am reviewing.  Apologies if my git-fu is weak.  I see the one trivial commit which is adding the blank line to make the list render properly.  The other commit is significant, but github said it did not belong to any branch in this repo, so I wasn't sure what to do with that...

**Comment by bethcerny** [comment]
Chris, it looks like you need to update the branch. I thought I'd let you do the branch update since it isn't clear to me what changed after reviewing.

**Comment by cjknight** [comment]
The bigger looking commits are just me syncing with main repo. Correct, the only change in this PR is that one single new line. I was curious to see how long this would take to snag two reviews if I didn't ping anyone about it. :)

**Pull request merged**
