### PR TITLE
some Julia updates for Polaris

### PR DESCRIPTION
**Pull request by cjknight**
Some updates to docs after trying to get a simple multi-node gpu-aware MPI test to run.

@michel2323 I think all the changes are minor updates except for the one at bottom regarding tmpdir. My limited experience was that I had to set TMPDIR to a globally accessible directory otherwise compute nodes would complain they couldn't access the default TMPDIR on the head node. Is there really an issue with how CUDA kernels get compiled and needing to create node-local temp directories to avoid clashing?

### CODE REVIEW

**Comment by michel2323** [comment]
If one does large-scale runs, yes. The compiled kernels are named with a hash, which is not long enough to avoid collisions.

**Comment by michel2323** [comment]
I can try to fix that in CUDA.jl.

**Comment by cjknight** [comment]
OK, thanks! I reverted that back to `TMPDIR=/local/scratch` for now.

**Comment by felker** [comment]
Is this ready to merge?

**Comment by cjknight** [comment]
Most likely yes. ...but I should probably do post-upgrade sanity check.

**Comment by cjknight** [comment]
Included updates from post-upgrade Polaris testing. This is good to go now.

**Review by felker — APPROVED** [review]

**Pull request merged**
