### PR TITLE
Adds `polaris/data-science-workflows/python.md`

### PR DESCRIPTION
**Pull request by saforem2**
Adds basic information about loading / interacting with pre-built `conda` environments.

### CODE REVIEW

**Review by bethcerny — COMMENTED** [review]
@saforem2 the directory name is just data-science not data-science-workflows

**Comment by saforem2** [comment]
@bethcerny apologies if I'm misunderstanding, but it looks like from `docs/polaris/`

```bash
$ ls docs/polaris
applications-and-libraries/  build-tools/         compiling-and-linking/      data-science-workflows/  debugging-tools/  hardware-overview/
performance-tools/           programming-models/  queueing-and-running-jobs/  getting-started.md       known-issues.md

$ ls docs/polaris/data-science-workflows
containers/  balsam.md  python.md
```

```bash
$ tree docs/polaris
docs/polaris
├── data-science-workflows
│   ├── balsam.md
│   ├── containers
│   │   └── containers.md
│   └── python.md
```

**Comment by bethcerny** [comment]
@saforem2 my bad...theta-gpu is only data-science...I'll fix this so that the directories on the machines are named the same moving forward to remove confusion. Thanks for reviewing.

**Review by bethcerny — APPROVED** [review]

**Review by saforem2 — COMMENTED** [review]
Changes:

- Removes hard-coded values for `NRANKS_PER_NODE`
  - Replaces with: `NRANKS_PER_NODE=$(nvidia-smi -L | wc -l)`
- Wrap **IMPORTANT** block in warning admonition
- Wrap `export MPICH_GPU_SUPPORT_ENABLED=1` in info admonition
- Wrap `./set_affinity_gpu_polaris.sh` in info admonition
- Replaces hard coded `num_gpus=4` in `cat ./set_affinity_gpu_polaris.sh`
  - Again, replaces with `num_gpus=$(nvidia-smi -L | wc -l)`

**Review by venkat-1 — APPROVED** [review]

**Pull request merged**
