### PR TITLE
Feature/b011 sn dnp

### PR DESCRIPTION
**Pull request by BruceRayWilson**
Updated SN login jpg.

### CODE REVIEW

**Comment by felker** [comment]
Is this ready to merge? Any suggestions for someone to review it?

**Comment by BruceRayWilsonAtANL** [comment]
> Is this ready to merge? Any suggestions for someone to review it?

Kyle, I slipped and added updates that are not to be published until after SambaNova Gen 2 (SN-30) is made public.  It will be merged after that happens.  Thanks for the comment.

**Comment by felker** [comment]
@BruceRayWilson with the SambaNova Gen2 system available now, what is the plan for this PR?

**Comment by BruceRayWilsonAtANL** [comment]
That can be deleted.
________________________________

**Pull request closed without merging**
