### PR TITLE
add self-build instructions for kokkos

### PR DESCRIPTION
**Pull request by zippylab**

### CODE REVIEW

**Review by cjknight — COMMENTED** [review]
Does this work for you with the latest version of Kokkos?

I'm seeing "multiple definition" errors with nvhpc/21.9 and nvhpc/22.5. I can get it to build adding "-DKokkos_ENABLE_IMPL_DESUL_ATOMICS=OFF". GNU builds just fine using your instructions.

[  3%] Building CXX object core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o
cd /home/knight/test/kokkos/build/core/src && /opt/cray/pe/craype/2.7.15/bin/CC -DKOKKOS_DEPENDENCE -I/home/knight/test/kokkos/build/core/src -I/home/knight/test/kokkos/core/src -I/home/knight/test/kokkos/build -I/home/knight/test/kokkos/core/src/../../tpls/desul/include -isystem /soft/compilers/cudatoolkit/cuda-11.6.2/include -O2 -gopt -mp -tp=zen2 -gpu=nordc -cuda -gpu=cc80 --c++17 -MD -MT core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o -MF CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o.d -o CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o -c /home/knight/test/kokkos/core/src/impl/Kokkos_Core.cpp
"/home/knight/test/kokkos/core/src/../../tpls/desul/include/desul/atomics/CUDA.hpp", line 523: error: function "desul::atomic_fetch_max(long *, long, desul::MemoryOrderRelaxed, desul::MemoryScopeDevice)" has already been defined
  __device__ inline long atomic_fetch_max(long* const dest,
                         ^

"/home/knight/test/kokkos/core/src/../../tpls/desul/include/desul/atomics/CUDA.hpp", line 530: error: function "desul::atomic_fetch_min(long *, long, desul::MemoryOrderRelaxed, desul::MemoryScopeDevice)" has already been defined
  __device__ inline long atomic_fetch_min(long* const dest,
                         ^

2 errors detected in the compilation of "/home/knight/test/kokkos/core/src/impl/Kokkos_Core.cpp".

**Comment by zippylab** [comment]
@cjknight did you manually load the cudatoolkit-standalone/11.6.2 atop the PrgEnv-nvhpc module? I found that to be necessary to get the build and link to work correctly using C++17.

**Comment by cjknight** [comment]
@zippylab Yup. The cudatoolkit-standalone module only brings in a new nvcc. The compile issue above is with nvc++ used by the Cray compiler wrapper.

**Review by cjknight — APPROVED** [review]
Looks good.

**Pull request merged**
