### PR TITLE
Aurora: add Spack PE documentation

### PR DESCRIPTION
**Pull request by koysean**
Adds a Spack PE page which gives instructions for accessing and inspecting software in the Spack PE, as well as some information on configuring user Spack installations on Aurora.

### CODE REVIEW

**Comment by cjknight** [comment]
Is this waiting on 1) update to mkdoc.yaml to include in aurora/build_tools and 2) pulling in content from Theta's spack page?

**Comment by koysean** [comment]
I moved the page to `aurora/applications-and-libraries/libraries` since that feels most appropriate to me and that's where the Spack documentation on Theta is.

Let me know if I should change anything else. Thanks!

**Review by cjknight — APPROVED** [review]

**Comment by zippylab** [comment]
@koysean can you update your branch w.r.t. main? I think that's needed before one of the merge checks can pass.

**Comment by koysean** [comment]
Could you run the workflow again? I rebased over main.

**Pull request merged**
