### PR TITLE
Update libensemble guide for Polaris

### PR DESCRIPTION
**Pull request by shuds13**

### CODE REVIEW

**Comment by felker** [comment]
Just checking: still in progress?

**Comment by shuds13** [comment]
Yes I think this is ready. I don't suppose there is a way to see the rendered output. I can see on github, but sometimes markdown gets rendered a bit differently in different places.

**Comment by felker** [comment]
The only way I am aware of is to deploy the Mkdocs locally, by following the instructions on the README. It is actually simple once you have cloned the repo and setup Python.

Let me know when you have reviewed the changes offline

**Comment by shuds13** [comment]
I've reviewed locally, and this is ready now. Thanks.

**Review by felker — APPROVED** [review]

**Comment by felker** [comment]
I unfortunately noticed a few problems after merging:
- https://www.alcf.anl.gov/support/user-guides/polaris/data-science-workflows/python/index.html is broken. Should be https://docs.alcf.anl.gov/polaris/data-science-workflows/python/
- Stray tilde in "E.g.,~"
- Not sure why  \`/path/to-venv\` did not render correctly in a `<details>` block...
- Spacing error:
(also should capitalize GitHub)
image

**Comment by shuds13** [comment]
@felker thanks, I'll make a new PR with those fixes.

**Pull request merged**
