### PR TITLE
Add libEnsemble guide under workflows

### PR DESCRIPTION
**Pull request by shuds13**

### CODE REVIEW

**Review by felker — APPROVED** [review]
Suggestions:
- Add an internal link to https://www.alcf.anl.gov/support/user-guides/polaris/data-science-workflows/python/index.html in the first subsection
- Make an explicit mention that the libensemble built in Conda was built without `[extras]`, including PETSc support
- Add a space after `-l` in the PBS script options, and generally reorganize them to be in a similar order to https://www.alcf.anl.gov/support/user-guides/polaris/queueing-and-running-jobs/example-job-scripts/index.html
```
#!/bin/bash -l
#PBS -l select=1:system=polaris
#PBS -l place=scatter
#PBS -l walltime=0:30:00
#PBS -l filesystems=home:grand
#PBS -q debug
#PBS -A Catalyst
```

**Comment by shuds13** [comment]
I've updated based on suggestions.

**Comment by felker** [comment]
Ready to merge?

**Comment by shuds13** [comment]
Yes, I think this is ready. Thanks!

**Pull request merged**
