### PR TITLE
Paraview on Polaris

### PR DESCRIPTION
**Pull request by srizzi88**

### CODE REVIEW

**Review by mvictoras — CHANGES_REQUESTED** [review]
@srizzi88 looks great, fantastic job!

My only comment is that this sentence:
`Connect your Paraview client to the server configuration you created above.`
might need some clarification or screenshot. Some users might not know how to connect.

**Comment by srizzi88** [comment]
all change requests addressed

**Review by mvictoras — APPROVED** [review]
Looks great!

**Review by josephinsley — APPROVED** [review]
Looks good

**Pull request merged**
